version: 0.2

phases:
  install:
    commands:
      - echo installing dependencies

  pre_build:
    commands:
      - echo start prebuild and end it

  build:
    commands:
      - echo Running build

  post_build:
    commands:
      - echo Build complete successfully

artifacts:
  files:
    - "**/*"
  base-directory: .
